### ISSUE TITLE
how to use my own dataset

### ISSUE THREAD

**Issue by cheeseywy** [raymin0223/patch-mix_contrastive_learning#6]
Hi, @raymin0223. Thank you for providing good research and opensource code!
If I want to train and test on my own dataset, which parts of the code should I modify? Also, do I need to make any modifications to my own dataset?
Thanks! ^_^

**Comment by raymin0223** [comment]
Hi @cheeseywy,

Sorry for the late reply, and thanks for your interests!

If you want to use your own dataset, you should modify `util/icbhi_dataset.py` and `util/icbhi_util.py`.
The important factors in each file are as follows:

#### In `util/icbhi_dataset.py`
- You should define `self.audio_images` as the list with mel-spectrograms.
- To convert raw audios to mel-spectrograms, you can use some useful functions, defined in`util/icbhi_util.py`.
- Since ICBHI contains multiple individual cycles in one sample, so you should modify the preprocessing codes if you want to treat a sample as one event .

#### In `util/icbh_util.py`
- In this file, we defined various preprocessing function only for ICBHI dataset.
- There are two types of functions, especially with librosa or torchaudio libraries (_e.g._, `get_individual_cycles_librosa` or `get_individual_cycles_torchaudio`).
- You can refer to all these functions to preprocess your own dataset.

After making new dataset and util files, I believe that it will work well.

**Comment by cheeseywy** [comment]
Thanks for your patient reply! ^_^

**Comment by raymin0223** [comment]
Thank you and I will close this issue. Please reopen or make issues if you have further questions!
